blank_issues_enabled: false
contact_links:
  - name: ABPVN Fanpage
    url: https://fb.com/abpvn.org
    about: Please report ads or anything else via message here
  - name: ABPVN Forum
    url: https://voz.vn/t/abpvn-chan-quang-cao-cho-nguoi-viet.25778/
    about: Please report ads or anything else via thread here