name: Report ads on website
description: Report ads exist on website when enable ABPVN List
title: 'Exist ads on website: [domain]'
labels: ["Exist ads"]
assignees:
  - hoang-rio
body:
  - type: checkboxes
    id: checklists
    attributes:
      label: Checklists
      description: Checklists before create issue
      options:
        - label: Updated ABPVN List to latest version
          required: true
        - label: Added prefix [NSFW] in issue title with site contain adult content
          required: true
        - label: Searched domain in both open and close issue with same issue type
          required: true
        - label: Reproduce rate is over 50%
          required: true
        - label: Replace [domain] in issue title with issue domain
          required: true
        - label: Uploaded screenshot, screen capture inside details tag and must be click to viewable in preview tab
          required: true
  - type: textarea
    id: description
    attributes:
      label: Ads description
      description: Tell about ads you see in website here
      placeholder: "Example: Banner top still display with ABPVN"
    validations:
      required: true
  - type: textarea
    id: reproduce-step
    attributes:
      label: Reproduce step
      description: Tell me how to reproduce issue
      value: |
        1. Go to website
        2. ...
        3. ...
    validations:
      required: true
  - type: input
    id: website-url
    attributes:
      label: Website url of issue
      placeholder: "https://example.com"
    validations:
      required: true
  - type: textarea
    id: sc-abpvn-enable
    attributes:
      label: Screenshot or screen capture when ABPVN enable
      description: Drag image or video inside details tag to upload
      value: |
        <details>
        <summary>Click to open</summary>

        <!-- Drag image or video here to upload -->

        <!-- If video too big you also upload to another service and paste url here -->

        </details>
  - type: textarea
    id: sc-abpvn-disable
    attributes:
      label: Screenshot or screen capture when ABPVN disabled
      description: Drag image or video inside details tag to upload
      value: |
        <details>
        <summary>Click to open</summary>

        <!-- Drag image or video here to upload -->

        <!-- If video too big you also upload to another service and paste url here -->

        </details>
  - type: markdown
    attributes:
      value: |
        **Enviroment**
  - type: input
    id: browers
    attributes:
      label: Browser
      description: Browser and version of it that can reproduce the issue
      placeholder: "Example: Firefox 101"
    validations:
      required: true
  - type: input
    id: adblocker
    attributes:
      label: Adblocker
      description: Adblocker and version of it
      placeholder: "Example: Adblock Plus 3.84"
    validations:
      required: true
  - type: textarea
    id: subscription-filter
    attributes:
      label: Active filter list
      description: List of using filter
      placeholder: |
        Example:
        * EasyList + ABPVN List
        * EasyPrivacy
        * Custom filter (https://custome-filter-url)
    validations:
      required: true
